### ISSUE TITLE
Can you provide extra data/information?

### ISSUE THREAD

**Issue by gdbinit** [rickmark/mojo_thor#1]
I just checked your mojo.kext dump and I don't see anything malicious there, although I couldn't find yet how that kext is installed (it looks like some debugging protocol via serial port).

The ThorUtil.efi is also clean, and the firmware update file is legit and unmodified.

Do you have any possibility to make a direct dump of the flash? Is it a MacBookPro with a SOIC flash or newer one with BGA only flash chip? SOIC models are easy to dump. This would allow to poke at the contents of the flash and sort out if there is any EFI rootkit resident there.

**Comment by gdbinit** [comment]
Just an update to this.
MojoKDP.kext is an Apple kernel extension. Your updated readme allowed me to find it because you described the missing piece, that you see it in Recovery mode.

The reason why you don't see this extension in the filesystem is because it only exists in the prelinkedkernel file, which contains all the kernel extensions in recovery mode in a single file. I extracted the MojoKDP.kext from that file and it matches the one you posted here.

**Comment by rickmark** [comment]
This is false.  Or if true, should never be out of Apple HQ.  You can find machines that exhibit the behavior by examining the fact that a non-infected computer does not contain a node in the IOKit registry for MojoKDP.  I encourage other MacBook owners to reboot to recovery and run `ioreg | grep MojoKDP` to validate.  It should also be noted that the firmware found on this computer is a few versions behind as described in [this article](https://duo.com/blog/the-apple-of-your-efi-mac-firmware-security-research) by @DuoSecurity.

**Comment by gdbinit** [comment]
I am not sure what you are talking about. I just reproduced your issue with MojoKDP.kext in different machines and the probability that I would be infected with the same rootkit as you is (near) zero.
The dump that you posted of MojoKDP.kext is the same legit code as found in official Apple images. Further, that code is not malicious at all. You only see MojoKDP.kext when booting in Recovery mode because that kext only exists in the prelinked kernel file shipped with recovery partition.

I know duo security article, I read its draft before publishing. What needs to be done is a hardware flash dump out of your EFI so its contents can be compared against legit versions and confirm if there is a resident EFI rootkit.

**Comment by rickmark** [comment]
To be utterly overt, the FBI has confirmed MojoKDP / Thor and Loki as malware.  I have received permission to publish from the San Francisco division, and you can plainly see that this is an old version of the firmware vs. your repository for that model.  You can also see the differences in the firmware dump as posted in the repository and I'd draw your attention to MOJO and STDK in the SMC as the decryption keys for a few LZMA compressed images in the firmware that are part of the DSMOS model of encryption of portions of the firmware.  It is needed to dump the contents of the SMC before we can fully evaluate the differences in the firmware.

**Comment by gdbinit** [comment]
Let me analyse the firmware dump you got out of eficheck. It's not perfect because stuff in nvram is cleared due to privacy reasons. I'm super curious about this, so I'm trying to sort out the puzzles pieces you left.

Can we chat over signal or otr?

**Comment by rickmark** [comment]
If you'd like to further contest this, please send you're evidence to 1 Infinite Loop:

[https://drive.google.com/open?id=0Bx1083F4dcGOenc5OEV0LVRqdG8](https://drive.google.com/open?id=0Bx1083F4dcGOenc5OEV0LVRqdG8)

**Comment by gdbinit** [comment]
I know the right people at 1 IL to help, I just need to find out what I need to ask them.

**Comment by rickmark** [comment]
I'll respectfully decline to go OTR or Signal.  Security research like this should be conducted in the public spotlight.  After all, I'm proud of my work and my cell phone number is listed publicly on my website.  Fortunately the sample (including the redacted regions) has been submitted to Apple, but feel free to analyze the "privacy redacted" version of the EFI dump at [bad.fd](https://github.com/rickmark/mojo_thor/blob/master/Firmware/bad.fd).  You will note that there are a few regions of difference, which again require knowledge of Apple's SMC for this model and the STDK and MOJO values from the SMC on the device.  Connect with the Clover folks as this is the primary thing protecting Apple's operating system from running on non-authorized hardware.

**Comment by gdbinit** [comment]
You are missing the point, there are certain reasons for talking in private. I have no problems exposing this rootkit, my past work speaks for itself. 

The EFI dump is not the SMC dump. SMC has a different firmware, which my repository doesn't have yet. There is indeed a SMC flasher inside EFI. What I am missing is your logic. There's a lot of stuff being mixed here. What needs to be done is first assure the EFI flash isn't compromised. Then you can move into hunting a SMC rootkit.

**Comment by rickmark** [comment]
This is in fact an internal tool used by Apple developers that has been weaponized.  MojoKDP provides a kernel debugger on the same box, and has no purpose on consumer machines
